### ISSUE TITLE
@OAuthRedirect interceptor

### ISSUE THREAD

**Issue by koriym** [ray-di/Ray.OAuthModule#10]
OAuth redirect page will be very same in any application ?
If so, Why not to have a procedure as a aspect rather than copy-past as follows ?

```php

use Ray\OAuthModule\annotation\OAuthRedirect; // import @OAuthRedirect annotations

class AuthController extends AbstractController
{
    /**
     * @OAuthRedirect
     */
    public function indexAction()
    {
        // be empty
    }
}
````

**Comment by kawanamiyuu** [comment]
Twitterより
https://twitter.com/BEARSunday/status/553366874298130432

> BEAR.Sunday ‏@BEARSunday  Jan 9
コントローラーの処理をアスペクトにするのはいいのか？という問題はあります。がとりあえずissueにしてみました　https://github.com/Ray-Di/Ray.OAuthModule/issues/10 … @kawanamiyuu

----

> ゆう ‏@kawanamiyuu  Jan 9
横断的な処理ではないためちょっとやり過ぎな感じもしますが、、ちょっと考えてみます。traitで共通処理として提供するのはありかもしれません >@BEARSunday

----

> BEAR.Sunday ‏@BEARSunday  Jan 9
@kawanamiyuu traitよりは__invokeメソッドが１つだけある単機能のサービスオブジェクトがいいと思います。

**Comment by koriym** [comment]
「アプリケーションを横断した同一処理」ということでアスペクトでもいいような気も？？

**Comment by kawanamiyuu** [comment]
確かに、扱うソーシャルサービスが１つの場合はインターセプタでの処理はどのアプリケーションでもほとんど場合同じになるためそうなのですが、複数のソーシャルサービスへのOAuthを扱う場合が気になっています。

```php
class AuthController extends AbstractController
{
    /**
     * Twitter OAuth
     * @OAuthRedirect
     */
    public function twitterAction()
    {
    }
    /**
     * Facebook OAuth
     * @OAuthRedirect
     */
    public function facebookAction()
    {
    }
}
```

のような場合に、インターセプタが自分がどちらのソーシャルサービス（Twitter or Facebook）にOAuthすべきかを知る良い方法があるのかというところです。

と考えていてその場合、アノテーションの引数で指定するようにすればいいのかな〜という気がしてきました。。（例：```@OAuthRedirect(service="Twitter")```）

**Comment by koriym** [comment]
別アノテーションにするのはどうでしょうか？
`@OAuthTwitterRedirect` / `@OAuthFbRedirect`

１つのアノテーションでやる場合は、２つのサービスをインジェクトしておいてプロパティの値で処理を分岐するような感じになってしまうと思います。

**Comment by kawanamiyuu** [comment]
なるほどまずはそれがシンプルで良さそうですね
別アノテーションで実装進めてみます:+1:

**Comment by kawanamiyuu** [comment]
今後の課題として、今の仕組みでは１サービスにつき{Module, Inject, Annotation, Interceptor}を１セットずつ追加実装する必要があるため、今後上手く抽象化してサービスを追加しやすい仕組みにしたいなという思いもあります:satisfied:

**Comment by koriym** [comment]
BEAR.Sunday専用のクラスなら、下記のように継承する方法もありますね。

```php
class Twitter extends AbstractOAuthTwitterRedirect
{
}
```

**Comment by koriym** [comment]
FacebookとTwitterのモジュールを別クラスにしていますが、これはどういう意味でしてるのでしょうか？

**Comment by kawanamiyuu** [comment]
１つのアプリケーションで複数のソーシャルサービスを使用するケースを想定して、使用したいモジュールを自由に選択してインストールできるようにしたいという目的でした。あと、最初、今後の拡張方針が手探りな中で、モジュールを分けたほうが実装が簡単だったという理由もあります。

一応当初から、ゆくゆくは**各サービス(Twitter, Facebook,...)の設定情報を配列かConfigCollectionオブジェクトのようなものでまとめて扱って、１つのモジュールクラスで複数のサービスをインストールできるように**したいという目論みもありました。

ここ数日で↑(**_太字部分_**)の実装イメージが固まってきましたのでそちらを先に対応してみたいと思うのですがどうでしょうか？PR作ってそこでまた相談したいです:)

**Comment by koriym** [comment]
> ここ数日で↑(太字部分)の実装イメージが固まってきましたのでそちらを先に対応してみたいと思うのですがどうでしょうか？

OKです！

**Comment by kawanamiyuu** [comment]
#11 で対応しました

**Comment by kawanamiyuu** [comment]
#11 は対応方針の見直しが必要そうなため、マージせず一旦closeしました。
#11 に代わる別PRを作る予定ですので、このissueももうしばらく対応は保留の状態とします。

**Comment by kawanamiyuu** [comment]
@koriym  #12 にて認証画面へのリダイレクト処理が↓のとおりシンプルに記述できるようになりましたので本件クローズでよいかと思いますがどうでしょう？

```php
    use TwitterOAuthInject;

    public function foo()
    {
        // redirects to the authorization page
        $this->twitterOAuth->authorize();
        exit(0);
    }
```

**Comment by koriym** [comment]
:+1:
